# Generated by Django 3.1.4 on 2020-12-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='champs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_name', models.CharField(max_length=100)),
                ('champ_splitpush', models.IntegerField()),
                ('champ_pick', models.IntegerField()),
                ('champ_siege', models.IntegerField()),
                ('champ_control', models.IntegerField()),
                ('champ_teamfight', models.IntegerField()),
            ],
        ),
    ]
